version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    image: pushkar231299/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: pushkar
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
