version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=pushkar
      - MONGO_PASS=password
      - SESSION_SECRET= secret
    command: npm run dev
